### ISSUE TITLE
Error 401 Unauthorized

### ISSUE THREAD

**Issue by Twen1x** [JakyeRU/Laravel-Discord-Authentication#1]
I did everything according to the instructions, and gives an error 401
what's wrong
Client error: `POST https://discord.com/api/oauth2/token` resulted in a `401 Unauthorized` response:
    {"error": "invalid_client"}

**Comment by ValentinNeaga** [comment]
Hello. I tried to install it and it's working as expected on my end. Can you describe how you've set it up?

**Comment by Twen1x** [comment]
I did a little stupid thing, everything didn't work for me, I was looking for where the code breaks
It turned out to be on line 42, I started looking for an error and constantly displayed this error
I had to change line 43 to
echo $error;

**Comment by ValentinNeaga** [comment]
No worries! I'm glad you managed to fix it.
