### ISSUE TITLE
How do I get guild information?

### ISSUE THREAD

**Issue by Yan2111** [JakyeRU/Laravel-Discord-Authentication#2]
Hi
Tell me how to add guilds, instead of email

**Comment by ValentinNeaga** [comment]
Hello. You'll have to add the `guilds` scope on line 24.
https://github.com/JakyeRU/Laravel-Discord-Authentication/blob/5f449c9e624efd7c7ebb45daf7583886f20a582f/app/Http/Controllers/DiscordController.php#L24
```php
 "scope" => "identifiy&email&guilds" 
```

You also need to add the `guilds` scope to the login button on line 57:
https://github.com/JakyeRU/Laravel-Discord-Authentication/blob/5f449c9e624efd7c7ebb45daf7583886f20a582f/resources/views/welcome.blade.php#L57
```blade
<a class="underline" href="https://discord.com/oauth2/authorize?client_id={{env("DISCORD_CLIENT_ID")}}&redirect_uri={{env("DISCORD_REDIRECT_URI")}}&response_type=code&scope=identify%20email%20guilds">Authenticate with Discord</a>
```

Then you can make a request to https://discord.com/api/users/@me/guilds with the same access token you used for authentication.
```php
$userData = Http::withToken($accessTokenData -> access_token) -> get('https://discord.com/api/users/@me/guilds');
if ($userData -> clientError() || $userData -> serverError()) {return redirect() -> route("index");};
```

Example response:
```json
[
   {
      "id":"81384788765712384",
      "name":"Discord API",
      "icon":"a363a84e969bcbe1353eb2fdfb2e50e6",
      "owner":false,
      "permissions":104189632,
      "features":[
         "WELCOME_SCREEN_ENABLED",
         "BANNER",
         "VANITY_URL",
         "PREVIEW_ENABLED",
         "PRIVATE_THREADS",
         "VIP_REGIONS",
         "ANIMATED_ICON",
         "NEW_THREAD_PERMISSIONS",
         "INVITE_SPLASH",
         "MEMBER_PROFILES",
         "THREE_DAY_THREAD_ARCHIVE",
         "SEVEN_DAY_THREAD_ARCHIVE",
         "THREADS_ENABLED",
         "NEWS",
         "MEMBER_VERIFICATION_GATE_ENABLED",
         "COMMUNITY",
         "ROLE_ICONS"
      ],
      "permissions_new":"966471831232"
   }
]
```

**Comment by ValentinNeaga** [comment]
Hello, did it solve your issue, @Yan2111 ?

**Comment by Yan2111** [comment]
Hi, sorry I haven't been in touch for so long. I did as you wrote. But I get this error - Trying to get property 'id' of non-object

I have already tried to do it myself, but otherwise how did you write to me. And there was exactly the same mistake

**Comment by Yan2111** [comment]
Here is my request function

```php
    public function login(Request $request) {
        if (Auth::check()) {return redirect() -> route("main.index");};
        if ($request -> missing("code") && $request -> missing("access_token")) {
            return redirect() -> route("main.index");
        };

        $this -> tokenData["client_id"] = env("DISCORD_CLIENT_ID");
        $this -> tokenData["client_secret"] = env("DISCORD_CLIENT_SECRET");
        $this -> tokenData['grant_type'] = 'authorization_code';
        $this -> tokenData["code"] = $request -> get("code");
        $this -> tokenData["redirect_uri"] = env("DISCORD_REDIRECT_URI");


        $client = new GuzzleHttp\Client();

        try {
            $accessTokenData = $client -> post($this -> tokenURL,["form_params" => $this -> tokenData]);
            $accessTokenData = json_decode($accessTokenData -> getBody());
        } catch (\GuzzleHttp\Exception\ClientException $error) {
            return redirect() -> route("main.index");
        };

        $userData = Http::withToken($accessTokenData -> access_token) -> get($this -> apiURLBase);
        if ($userData -> clientError() || $userData -> serverError()) {
            return redirect() -> route("main.index");
        };

        $userData = Http::withToken($accessTokenData -> access_token) -> get('https://discord.com/api/users/@me/guilds');
        if ($userData -> clientError() || $userData -> serverError()) {
            return redirect() -> route("main.index");
        };



        $userData = json_decode($userData);

        $user = User::updateOrCreate(
            [
                'id' => $userData -> id,
            ],
            [
                'username' => $userData -> username,
                'discriminator' => $userData -> discriminator,
                'email' => $userData -> email,
                'avatar' => $userData -> avatar,
                'verified' => $userData -> verified,
                'locale' => $userData -> locale,
                'mfa_enabled' => $userData -> mfa_enabled,
                'refresh_token' => $accessTokenData -> refresh_token
            ]
        );


        Auth::login($user);


        return redirect() -> route("main.index");
    }
   ```

**Comment by ValentinNeaga** [comment]
> Here is my request function
> 
> ```
>     public function login(Request $request) {
>         if (Auth::check()) {return redirect() -> route("main.index");};
>         if ($request -> missing("code") && $request -> missing("access_token")) {
>             return redirect() -> route("main.index");
>         };
> 
>         $this -> tokenData["client_id"] = env("DISCORD_CLIENT_ID");
>         $this -> tokenData["client_secret"] = env("DISCORD_CLIENT_SECRET");
>         $this -> tokenData['grant_type'] = 'authorization_code';
>         $this -> tokenData["code"] = $request -> get("code");
>         $this -> tokenData["redirect_uri"] = env("DISCORD_REDIRECT_URI");
> 
> 
>         $client = new GuzzleHttp\Client();
> 
>         try {
>             $accessTokenData = $client -> post($this -> tokenURL,["form_params" => $this -> tokenData]);
>             $accessTokenData = json_decode($accessTokenData -> getBody());
>         } catch (\GuzzleHttp\Exception\ClientException $error) {
>             return redirect() -> route("main.index");
>         };
> 
>         $userData = Http::withToken($accessTokenData -> access_token) -> get($this -> apiURLBase);
>         if ($userData -> clientError() || $userData -> serverError()) {
>             return redirect() -> route("main.index");
>         };
> 
>         $userData = Http::withToken($accessTokenData -> access_token) -> get('https://discord.com/api/users/@me/guilds');
>         if ($userData -> clientError() || $userData -> serverError()) {
>             return redirect() -> route("main.index");
>         };
> 
> 
> 
>         $userData = json_decode($userData);
> 
>         $user = User::updateOrCreate(
>             [
>                 'id' => $userData -> id,
>             ],
>             [
>                 'username' => $userData -> username,
>                 'discriminator' => $userData -> discriminator,
>                 'email' => $userData -> email,
>                 'avatar' => $userData -> avatar,
>                 'verified' => $userData -> verified,
>                 'locale' => $userData -> locale,
>                 'mfa_enabled' => $userData -> mfa_enabled,
>                 'refresh_token' => $accessTokenData -> refresh_token
>             ]
>         );
> 
> 
>         Auth::login($user);
> 
> 
>         return redirect() -> route("main.index");
>     }
> ```

This is because you are assigning a new value to `$userData` (an array of guilds) which doesn't contain any `id` property. You can try to remove/modify that part of the code:

```php
public function login(Request $request) {
        if (Auth::check()) {return redirect() -> route("main.index");};
        if ($request -> missing("code") && $request -> missing("access_token")) {
            return redirect() -> route("main.index");
        };

        $this -> tokenData["client_id"] = env("DISCORD_CLIENT_ID");
        $this -> tokenData["client_secret"] = env("DISCORD_CLIENT_SECRET");
        $this -> tokenData['grant_type'] = 'authorization_code';
        $this -> tokenData["code"] = $request -> get("code");
        $this -> tokenData["redirect_uri"] = env("DISCORD_REDIRECT_URI");


        $client = new GuzzleHttp\Client();

        try {
            $accessTokenData = $client -> post($this -> tokenURL,["form_params" => $this -> tokenData]);
            $accessTokenData = json_decode($accessTokenData -> getBody());
        } catch (\GuzzleHttp\Exception\ClientException $error) {
            return redirect() -> route("main.index");
        };

        $userData = Http::withToken($accessTokenData -> access_token) -> get('https://discord.com/api/users/@me/guilds');
        if ($userData -> clientError() || $userData -> serverError()) {
            return redirect() -> route("main.index");
        };

        $userData = json_decode($userData);

        return $userData;
}
```

**Comment by Yan2111** [comment]
Yes, that's how I get the data. It remains to save this data in the database. Thanks

**Comment by ValentinNeaga** [comment]
Glad I could help!

**Comment by Yan2111** [comment]
Hi, after a while I came back to the entrance again, I stopped there.
But when I try to save the guild data, I get an error
`Trying to get property 'id' of non-object`
Be kind, tell me how to save servers on which the user has administrator rights.
I searched the internet, but I didn't find it for laravel(
Please help me

**Comment by ValentinNeaga** [comment]
Hello @Yan2111, 

Can you post the code that's causing the error?

As for getting the guilds where the user is an administrator, you can check the "permissions" field in the response. It'll be 8 if the user has the ADMINISTRATOR permission.

**Comment by Yan2111** [comment]
`    public function login(Request $request) {
        if (Auth::check()) {return redirect() -> route("main.index");};
        if ($request -> missing("code") && $request -> missing("access_token")) {
            return redirect() -> route("main.index");
        };

        $this -> tokenData["client_id"] = env("DISCORD_CLIENT_ID");
        $this -> tokenData["client_secret"] = env("DISCORD_CLIENT_SECRET");
        $this -> tokenData['grant_type'] = 'authorization_code';
        $this -> tokenData["code"] = $request -> get("code");
        $this -> tokenData["redirect_uri"] = env("DISCORD_REDIRECT_URI");


        $client = new GuzzleHttp\Client();

        try {
            $accessTokenData = $client -> post($this -> tokenURL,["form_params" => $this -> tokenData]);
            $accessTokenData = json_decode($accessTokenData -> getBody());
        } catch (\GuzzleHttp\Exception\ClientException $error) {
            return redirect() -> route("main.index");
        };

        $userData = Http::withToken($accessTokenData -> access_token) -> get('https://discord.com/api/users/@me/guilds');
        if ($userData -> clientError() || $userData -> serverError()) {
            return redirect() -> route("main.index");
        };

        $userData = json_decode($userData);

        $user = User::updateOrCreate(
            [
                'id' => $userData -> id,
            ],
            [
                'username' => $userData -> username,
                'discriminator' => $userData -> discriminator,
                'email' => $userData -> email,
                'avatar' => $userData -> avatar,
                'verified' => $userData -> verified,
                'locale' => $userData -> locale,
                'mfa_enabled' => $userData -> mfa_enabled,
                'refresh_token' => $accessTokenData -> refresh_token
            ]
        );

        $guild = Guild::updateOrCreate(
            [
                'id' => $userData -> id,
            ],
            [
                'name' => $userData -> name,
                'icon' => $userData -> icon,
                'owner' => $userData -> owner,
                'permissions' => $userData -> permissions,
                'features' => $userData -> features,
                'permissions_new' => $userData -> permissions_new
            ]
        );

        Auth::login($user);


        return redirect() -> route("main.index");
    }`

**Comment by Yan2111** [comment]
My authorization link

https://discord.com/oauth2/authorize?client_id=905792************&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fapi%2Flogin&response_type=code&scope=identify%20email%20guilds

**Comment by ValentinNeaga** [comment]
You are receiving the `Trying to get property 'id' of non-object` error because you are overwriting the `$userData` variable with the response from `https://discord.com/api/users/@me/guilds` before saving the user to the database.

```php
public function login(Request $request) {
    if (Auth::check()) {return redirect()->route("main.index");};
    if ($request->missing("code") && $request->missing("access_token")) {return redirect()->route("main.index");};

    $this->tokenData["client_id"] = env("DISCORD_CLIENT_ID");
    $this->tokenData["client_secret"] = env("DISCORD_CLIENT_SECRET");
    $this->tokenData["code"] = $request->get("code");
    $this->tokenData["redirect_uri"] = env("DISCORD_REDIRECT_URI");

    $client = new GuzzleHttp\Client();

    try {
        $accessTokenData = $client->post($this->tokenURL, ["form_params" => $this->tokenData]);
        $accessTokenData = json_decode($accessTokenData->getBody());
    } catch (\GuzzleHttp\Exception\ClientException $error) {
        return redirect()->route("main.index");
    };

    $userData = Http::withToken($accessTokenData->access_token)->get($this->apiURLBase);
    if ($userData->failed()) {return redirect()->route("main.index");};

    $guildData = Http::withToken($accessTokenData->access_token)->get($this->apiURLBase . '/guilds');
    if ($guildData->failed()) {return redirect()->route("main.index");};

    $userData = json_decode($userData);
    $guildData = json_decode($guildData);

    return response()->json([
        [$userData],
        [$guildData]
    ]);

    // Remove the return statement and save your User and Guild data here.
}
```

**Comment by Yan2111** [comment]
OK, but I still get the error `Trying to get property 'id' of non-object` 

```
        $userData = json_decode($userData);
        $guildData = json_decode($guildData);


        $user = User::updateOrCreate(
            [
                'id' => $userData -> id,
            ],
            [
                'username' => $userData -> username,
                'discriminator' => $userData -> discriminator,
                'email' => $userData -> email,
                'avatar' => $userData -> avatar,
                'verified' => $userData -> verified,
                'locale' => $userData -> locale,
                'mfa_enabled' => $userData -> mfa_enabled,
                'refresh_token' => $accessTokenData -> refresh_token
            ]
        );

        $guild = Guild::updateOrCreate(
            [
                'id' => $guildData -> id,
            ],
            [
                'name' => $guildData -> name,
                'icon' => $guildData -> icon,
                'owner' => $guildData -> owner,
                'permissions' => $guildData -> permissions,
                'features' => $guildData -> features,
                'permissions_new' => $guildData -> permissions_new
            ]
        );

        Auth::login($user);
```

I'm writing this code, and on `'id' => $guildData -> id,` writes an error 
Sorry for my English, I'm writing from a translator)

**Comment by ValentinNeaga** [comment]
Yes, that is expected as `$guildData` is an array of guilds, therefore it has no `id` property, but the guilds inside it do. A foreach loop on `$guildData` should solve this issue.

**Comment by Yan2111** [comment]
Thanks
